### ISSUE TITLE
about the cnum

### ISSUE THREAD

**Issue by tantao14** [dongliangchang/Mutual-Channel-Loss#2]
hello ! in CUB-200-2011.py line 198, you set cnum  = 3, which is not equal to the categories num, which is not same as your paper said, could you please tell me why?

**Comment by dongliangchang** [comment]
hi, the cnum is ξ,&nbsp; which is the number of feature channels used to represent each class.
And feature channels = ξ * the categories nums,&nbsp; where the model TRAINED FROM SCRATCH.
Please see Section III and&nbsp; Ablation Study for details.





------------------
 


Dongliang Chang

PRIS lab, BUPT



18513855782

No.10 Xitucheng Road, Haidian District, Beijing, China


 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by tantao14** [comment]
get, thank you
